######################################################################
# Automatically generated by qmake (2.01a) jeu. févr. 15 18:38:48 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += GUICase.hpp GUIMatrixLayout.hpp GUIWindow.hpp RGB.hpp
SOURCES += GUI.cpp GUICase.cpp GUIMatrixLayout.cpp GUIWindow.cpp RGB.cpp
