######################################################################
# Automatically generated by qmake (2.01a) ven. juin 15 11:45:25 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . \
              src \
              src/mainWindow \
              src/settingWindow \
              src/mainWindow/layout \
              src/mainWindow/server \
              src/settingWindow/fileSetting \
              src/settingWindow/layout
INCLUDEPATH += . \
               src/settingWindow \
               src/settingWindow/layout \
               src/mainWindow \
               src/mainWindow/layout \
               src/mainWindow/server \
               src/settingWindow/fileSetting

# Input
HEADERS += src/mainWindow/GUIWindow.hpp \
           src/settingWindow/GUISettingWindow.hpp \
           src/mainWindow/layout/GUIImageMatrix.hpp \
           src/mainWindow/server/GUITCPServer.hpp \
           src/settingWindow/fileSetting/GUIConfigFileSettingBuilder.hpp \
           src/settingWindow/fileSetting/GUIFileSettingBuilder.hpp \
           src/settingWindow/layout/GUIInputSettingLayout.hpp \
           src/settingWindow/layout/GUIProcessSettingLayout.hpp \
           src/settingWindow/layout/GUISettingLayout.hpp \
           src/settingWindow/layout/GUISettingLayoutFactory.hpp \
           src/settingWindow/layout/GUIWavFileSettingLayout.hpp
SOURCES += src/GUI.cpp \
           src/mainWindow/GUIWindow.cpp \
           src/settingWindow/GUISettingWindow.cpp \
           src/mainWindow/layout/GUIImageMatrix.cpp \
           src/mainWindow/server/GUITCPServer.cpp \
           src/settingWindow/fileSetting/GUIConfigFileSettingBuilder.cpp \
           src/settingWindow/layout/GUIInputSettingLayout.cpp \
           src/settingWindow/layout/GUIProcessSettingLayout.cpp \
           src/settingWindow/layout/GUISettingLayoutFactory.cpp \
           src/settingWindow/layout/GUIWavFileSettingLayout.cpp
