######################################################################
# Automatically generated by qmake (2.01a) mar. févr. 13 13:17:53 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Case.hpp Matrix.hpp RGB.hpp Window.hpp
SOURCES += Case.cpp GUI.cpp Matrix.cpp RGB.cpp Window.cpp
